In [2]:
import numpy as np
import pandas as pd
import matplotlib as mat
import requests as req
import sqlalchemy as sq 
import scipy as sc
 
import sys

In [3]:
def fun(x):
    if (x<0):
        value=0
    elif(x<5):
        value= 5
    else:
        value=10
        
    return value
fun(7)

10

In [4]:
def distance(x,y,z):
    def distancexy(x,y):
        return np.sqrt( ( x[0]-y[0])**2 +( x[1]-y[1])**2   )
    d0=distancexy(x,y)
    d1=distancexy(x,z)
    d2=distancexy(y,z)
    return [d0,d1,d2]

x=(3,4)
y=(4,7)
z=(2,8)

d=distance(x,y,z)
print(d)
d


[3.1622776601683795, 4.123105625617661, 2.23606797749979]


[3.1622776601683795, 4.123105625617661, 2.23606797749979]

In [5]:
 a={1,2,3}
 b=a
 c={2,1,3}
 print(id(a))
 print(id(b))
 print(id(c))
 print(a is b)
 
 print(a is c)
 print(a == c)

2362728626208
2362728626208
2362728625088
True
False
True


In [6]:
add=lambda x,y:x-y
add(4,6)

-2

#  funtion as argument to funtion 

In [7]:
m=np.max

print(m([1,3,56,7,4,2]))


def newfun(fun,x):
    return fun(x)+1
newfun(np.sin,np.pi/2)
newfun(np.cos,np.pi/2)

56


1.0

In [8]:
n=3
def fun():
    
    print(n)
    print(n)
    
fun()
n

3
3


3

In [9]:
dict={ 1:"one",2:"two",3:"three",4:"four",5:{"hello","hi" ,"indra"}}
for( value )in dict.items():
    print(f'key value  {value} ')
print(dict)
dict.items()

key value  (1, 'one') 
key value  (2, 'two') 
key value  (3, 'three') 
key value  (4, 'four') 
key value  (5, {'hi', 'indra', 'hello'}) 
{1: 'one', 2: 'two', 3: 'three', 4: 'four', 5: {'hi', 'indra', 'hello'}}


dict_items([(1, 'one'), (2, 'two'), (3, 'three'), (4, 'four'), (5, {'hi', 'indra', 'hello'})])

In [10]:
st={ 1,2,4,54,4,4,52,1,1,4,6,78,5,4,2}
st.add(399)
s={444,555}
print(s.clear())
s=s.union(st.copy())
print(s)
print(st)

None
{1, 2, 4, 5, 6, 78, 399, 52, 54}
{1, 2, 4, 5, 6, 78, 399, 52, 54}


In [11]:
sorted(([1,3],[55,6],[2,0],[4,1],[34,5]) ,key=lambda x: x[0] )

[[1, 3], [2, 0], [4, 1], [34, 5], [55, 6]]

In [12]:
def deff2nd(f,x,h=1e-6):
    result=(f(x-h)-2*f(x) +f(x+h) )/(h*2)

    return result
def g(x):
    return x**2
x=1.2
d2g=deff2nd(g,x)
d2g

9.999778782798785e-07

In [13]:

A=np.array([[1,2,3],[4,5,6]])
B=np.array([[1,2,3],[4,5,6]])
print(A,"\n",B)
a=4
A+B

[[1 2 3]
 [4 5 6]] 
 [[1 2 3]
 [4 5 6]]


array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [14]:
r=eval("[2,3,4,5]")
print(r)
type(r)

[2, 3, 4, 5]


list

In [15]:
from threading import*
n=10
def display():
    for i  in range(n):
        print(f"child class {i}")
        print(t.name)
        print(t.ident)
        print(enumerate)
    print("outsise ",i)

t=Thread(target=display)
t.start()
# n=int(input("Give me a number "))
for i in range(n):
    print(f"parent class {i}")
    

child class 0
Thread-3
2400
<function enumerate at 0x0000022615EE6310>parent class 0
parent class 1
parent class 2
parent class 3
child class 1
Thread-3
2400
<function enumerate at 0x0000022615EE6310>
child class 2
Thread-3
2400
<function enumerate at 0x0000022615EE6310>
parent class 4
parent class 5
parent class 6
parent class 7
parent class 8
parent class 9

child class 3
Thread-3
2400
<function enumerate at 0x0000022615EE6310>
child class 4
Thread-3
2400
<function enumerate at 0x0000022615EE6310>
child class 5
Thread-3
2400
<function enumerate at 0x0000022615EE6310>
child class 6
Thread-3
2400
<function enumerate at 0x0000022615EE6310>
child class 7
Thread-3
2400
<function enumerate at 0x0000022615EE6310>
child class 8
Thread-3
2400
<function enumerate at 0x0000022615EE6310>
child class 9
Thread-3
2400
<function enumerate at 0x0000022615EE6310>
outsise  9


In [16]:
x=5;y=6;z=7
a,b,c=5,6,7
print(a,b,c)
a,b,c= c,a,b


5 6 7


In [17]:
def factor(n):
     a=0;b=1
     while(True):
         yield a
         print(a)
         f=a+b
         a=b
         b=f
        

 
print(next(factor(100)))
print(next(factor(100)))
print(next(factor(100)))
print(next(factor(100)))

0
0
0
0


In [1]:
import tkinter as tk

from matplotlib.pyplot import text
root=tk.Tk()
root.geometry('500x500')
root.title("Calculate derivatives ")

# label
Coeff_label=tk.Label(root,text="Enter A value")
 

tk.mainloop()

In [2]:
from cProfile import label
from json.tool import main
import pyqrcode
import png
from pyqrcode import QRCode
import os 
from tkinter import messagebox,Toplevel
from tkinter import*
#program start fron here 
root = Tk()
root.geometry('500x400')
root.title("welcome to our Qr-Code generator")
root.wm_iconbitmap('logo.ico')
root.configure(bg='black')
#######################################
#funtions
def generateQr():
    Qr_ID=Qr_Id_Entry_box.get()
    Qr_Name=Qr_Name_Entry_box.get()
    if(Qr_ID==""  and  Qr_Name==""):
        messagebox.showerror("Error box " ,"please provide Name and  Id")
        return 
    Qr_Message=Qr_Message_Entry_box.get()
    Final='Name: '+Qr_Name+'\nID:'+Qr_ID+'\nMessage: '+Qr_Message
    url=pyqrcode.create(Final)
    path=r'C:\Users\indra\OneDrive\Desktop' 
    cc='{}\{}{}.png'.format(path,Qr_Name,Qr_ID)
    list =os.listdir(path)
    if('{}{}.png'.format(Qr_Name,Qr_ID) in list ):
        messagebox.showinfo('notification','Pleease choose another Name Aur ID')
    else:
        url.png(cc, scale=5) # url.png('hh.png',scale=5,module_color=(0,25,255),backgroun=(0,255,47,255))
        message='Qr code saved as :'+Qr_Name+Qr_ID+'.png'
        Qr_Notification_message_label.configure(text=message) 
        res=messagebox.askyesno('Notilication','Qr code generated you can see by clicking yes  ') 
        if(res==True):
            top=Toplevel()
            top.geometry('400x400')
            top.configure(bg='white')
            img =PhotoImage(file=cc)
            label1=Label(top,image=img,bg='white')
            label1.place(x=10,y=30)
            ClearIdName()
            top.mainloop()
           


def ClearIdName():
    Qr_Id_Entry_box.delete(0,'end')
    Qr_Name_Entry_box.delete(0,'end')
    Qr_Message_Entry_box.delete(0,'end')
    Qr_Notification_message_label.configure(text='')


def QuitRoot():
    res=messagebox.askokcancel('Notification','Are you sure ,you want to Quit? ')
    if(res==True):
        root.destroy()
    else:
        pass

###########################################
####labels


Qr_Id_label = Label(master=root,text='Enter your Id: ' , bg='black' , fg='white'
                    ,width=20,height=1,font=('times',12,'italic bold'))
Qr_Id_label.place(x=10,y=20)

Qr_Name_label = Label(master=root,text='Enter your name: ' , bg='black' , fg='white'
                    ,width=20,height=1,font=('times',12,'italic bold'))
Qr_Name_label.place(x=10,y=60)


Qr_Message_label = Label(master=root,text='Enter your message: ' , bg='black' , fg='white'
                    ,width=20,height=1,font=('times',12,'italic bold'))
Qr_Message_label .place(x=10,y=100)

##QR notification lable
Qr_Notification_label = Label(master=root,text=' Notification:-- ' , bg='black' , fg='white'
                    ,width=20,height=1,font=('times',12,'italic bold'))
Qr_Notification_label.place(x=10,y=350)

##QR notification  message lable
Qr_Notification_message_label = Label(master=root,text='   ' , bg='powder blue' , fg='white'
                    ,width=25,height=1,font=('times',12,'italic bold'))
Qr_Notification_message_label.place(x=250,y=350)


#########################
#Entry Boxes

Qr_Id_Entry_box=Entry(master=root,width=25,bd=2,bg='pink',font=('times',12,'italic bold'))
Qr_Id_Entry_box.place(x=200,y=20)

##
Qr_Name_Entry_box=Entry(master=root,width=25,bd=2,bg='pink',font=('times',12,'italic bold'))
Qr_Name_Entry_box.place(x=200,y=60)

##
Qr_Message_Entry_box=Entry(master=root,width=25,bd=2,bg='pink',font=('times',12,'italic bold'))
Qr_Message_Entry_box.place(x=200,y=100)
####################################################
##button logo

Generate_Qr_Image=PhotoImage(file='generate.png')
Generate_Qr_Image=Generate_Qr_Image.subsample(2,2);

Clear_Id_NameImage=PhotoImage(file='clear.png')
Clear_Id_NameImage=Clear_Id_NameImage.subsample(2,2)

Quit_Root_Image=PhotoImage(file='cancel.png')
Quit_Root_Image=Quit_Root_Image.subsample(2,2)


##########################
#button
Genarate_Qrimage_button=Button(master=root,text='Generate',bd=5,width=100,command=generateQr,
                      activebackground='green',compound=RIGHT ,image=Generate_Qr_Image, font=('times',12,'bold'),bg='powder blue');
Genarate_Qrimage_button.place(x=10,y=280)

##
clear_Id_Name_button =Button(master=root,text='Clear',bd=5,width=100,command=ClearIdName,
                      activebackground='white', compound=RIGHT ,image=Clear_Id_NameImage, font=('times',12,'bold'),bg='powder blue');
clear_Id_Name_button.place(x=200,y=280)

##
Quit_root_BUtton=Button(master=root,text='Quit',bd=5,width=100,command=QuitRoot,
                      activebackground='red', compound=RIGHT ,image=Quit_Root_Image,font=('times',12,'bold'),bg='powder blue');
Quit_root_BUtton .place(x=400,y=280)
#####################################################################################
##Hover Effect
def Genarate_Qrimage_buttonEnter(e):
    Genarate_Qrimage_button['bg']='purple'
def Genarate_Qrimage_buttonLeave(e):
    Genarate_Qrimage_button['bg']='powder blue'

def clear_Id_Name_buttonEnter(e):
    clear_Id_Name_button['bg']='purple'
def clear_Id_Name_buttonLeave(e):
    clear_Id_Name_button['bg']='powder blue'

def Quit_root_BUttonEnter(e):
    Quit_root_BUtton['bg']='purple'
def Quit_root_BUttonLeave(e):
    Quit_root_BUtton['bg']='powder blue'

Genarate_Qrimage_button.bind('<Enter>',Genarate_Qrimage_buttonEnter)
Genarate_Qrimage_button.bind('<Leave>',Genarate_Qrimage_buttonLeave)

clear_Id_Name_button.bind('<Enter>',clear_Id_Name_buttonEnter)
clear_Id_Name_button.bind('<Leave>',clear_Id_Name_buttonLeave)

Quit_root_BUtton.bind('<Enter>',Quit_root_BUttonEnter)
Quit_root_BUtton.bind('<Leave>',Quit_root_BUttonLeave)

root.mainloop()

TclError: bitmap "logo.ico" not defined